### ISSUE TITLE
ReferenceError in local copy

### ISSUE THREAD

**Issue by balihoo-aharl** [balihoo/balihoo-creative#4]
I'm getting an error when trying to run a locally built copy, I'm using for development.

```
/Users/aharl/Development/balihoo-creative/lib/console.js:61
      } : options;
          ^
ReferenceError: options is not defined
  at new Console (/Users/aharl/Development/balihoo-creative/lib/console.js:61:11)
  at new module.exports (/Users/aharl/Development/balihoo-creative/lib/console.js:282:12)
  at Object.start (/Users/aharl/Development/balihoo-creative/lib/server.js:42:42)
  at Object.<anonymous> (/Users/aharl/Development/balihoo-creative/lib/index.js:17:14)
  at Object.<anonymous> (/Users/aharl/Development/balihoo-creative/lib/index.js:19:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/aharl/Development/balihoo-creative/index.js:3:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3
```

This looks like it maps to line 25 in 'src/console.coffee'. Are there steps to build and install this besides `make init`, `make build`, and `npm link`?

**Comment by AndyCobb** [comment]
Resolved by edce90a037031bd12c83aad38b3404a5bd4a9cd8
